"""伴时 (BanShi) — MVP web app.

Run:
    python3 app.py
Then open http://127.0.0.1:5000 in a browser (phone width recommended).

No external API key required — dialogue is generated by a local LLM via
Ollama (llm_engine.py), which falls back to the rule-based lines in
dialogue.py whenever Ollama is unreachable.
"""
import os
import secrets
from datetime import date, datetime, timezone
from functools import wraps
from pathlib import Path

from flask import (
    Flask, render_template, request, redirect, url_for, session, jsonify, g
)
from werkzeug.security import generate_password_hash, check_password_hash

import db
import dialogue
import llm_engine
import mailbox

SECRET_FILE = db.DATA_DIR / ".secret_key"
# Desktop build (desktop.py) sets this: no login, everything belongs to one local user.
SINGLE_USER = os.environ.get("BANSHI_SINGLE_USER") == "1"


def load_or_create_secret() -> str:
    if SECRET_FILE.exists():
        return SECRET_FILE.read_text().strip()
    key = secrets.token_hex(32)
    SECRET_FILE.write_text(key)
    return key


app = Flask(__name__)
app.secret_key = load_or_create_secret()


# ---------------------------------------------------------------- helpers
def get_db():
    if "db" not in g:
        g.db = db.get_db()
    return g.db


@app.teardown_appcontext
def close_db(_exc):
    conn = g.pop("db", None)
    if conn is not None:
        conn.close()


def current_user():
    if SINGLE_USER:
        if "local_user" not in g:
            g.local_user = db.get_or_create_local_user(get_db())
        return g.local_user
    uid = session.get("user_id")
    if not uid:
        return None
    row = get_db().execute("SELECT * FROM users WHERE id = ?", (uid,)).fetchone()
    return row


def login_required(view):
    @wraps(view)
    def wrapped(*args, **kwargs):
        if current_user() is None:
            return redirect(url_for("login"))
        return view(*args, **kwargs)
    return wrapped


def get_owned_agent(agent_id: int, user_id: int):
    """Fetch an agent row, scoped to the owning user (memory isolation)."""
    return get_db().execute(
        "SELECT * FROM agents WHERE id = ? AND user_id = ? AND deleted_at IS NULL",
        (agent_id, user_id),
    ).fetchone()


def get_recent_history(conn, agent_id: int, user_id: int, limit: int = 20):
    """Oldest-first list of recent messages, for feeding conversational context to the LLM."""
    rows = conn.execute(
        "SELECT sender, content FROM messages WHERE agent_id = ? AND user_id = ? "
        "ORDER BY id DESC LIMIT ?",
        (agent_id, user_id, limit),
    ).fetchall()
    return list(reversed(rows))


@app.context_processor
def inject_globals():
    user = current_user()
    unread_letters = get_db().execute(
        "SELECT COUNT(*) FROM letters WHERE user_id = ? AND read_at IS NULL", (user["id"],)
    ).fetchone()[0] if user else 0
    return {"current_user": user, "unread_letters": unread_letters, "single_user": SINGLE_USER,
            "styles": dialogue.STYLES,
             "attitudes": dialogue.ATTITUDES, "avatars": dialogue.AVATARS,
             "avatar_groups": dialogue.AVATAR_GROUPS}


# ------------------------------------------------------------ auth routes
@app.route("/")
def index():
    if current_user():
        return redirect(url_for("agents_list"))
    return redirect(url_for("login"))


@app.before_request
def skip_auth_pages_in_single_user_mode():
    if SINGLE_USER and request.endpoint in ("login", "register", "logout"):
        return redirect(url_for("agents_list"))


@app.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        if current_user():
            return redirect(url_for("agents_list"))
        return render_template("login.html")

    identifier = request.form.get("identifier", "").strip()
    password = request.form.get("password", "")
    conn = get_db()
    row = conn.execute(
        "SELECT * FROM users WHERE email = ? OR username = ?",
        (identifier, identifier),
    ).fetchone()
    if row is None or not check_password_hash(row["password_hash"], password):
        return render_template("login.html", error="账号或密码不对哦，再试一次。",
                                identifier=identifier)
    session["user_id"] = row["id"]
    return redirect(url_for("agents_list"))


@app.route("/register", methods=["POST"])
def register():
    email = request.form.get("email", "").strip()
    username = request.form.get("username", "").strip()
    password = request.form.get("password", "")

    if not email or not username or not password:
        return render_template("login.html", reg_error="邮箱、用户名、密码都要填写哦。",
                                show_register=True)

    conn = get_db()
    existing = conn.execute("SELECT id FROM users WHERE email = ?", (email,)).fetchone()
    if existing:
        return render_template("login.html", reg_error="这个邮箱已经注册过啦，直接登录吧。",
                                show_register=True)

    conn.execute(
        "INSERT INTO users (email, username, password_hash, created_at) VALUES (?, ?, ?, ?)",
        (email, username, generate_password_hash(password), db.now_iso()),
    )
    conn.commit()
    row = conn.execute("SELECT * FROM users WHERE email = ?", (email,)).fetchone()
    session["user_id"] = row["id"]
    return redirect(url_for("agents_list"))


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("login"))


# --------------------------------------------------------- agents routes
@app.route("/agents")
@login_required
def agents_list():
    user = current_user()
    conn = get_db()
    rows = conn.execute(
        "SELECT * FROM agents WHERE user_id = ? AND deleted_at IS NULL ORDER BY created_at DESC",
        (user["id"],),
    ).fetchall()
    return render_template("agents.html", agents=rows)


@app.route("/agents/new", methods=["GET", "POST"])
@login_required
def agent_new():
    user = current_user()
    if request.method == "GET":
        return render_template("agent_form.html", agent=None)

    name = request.form.get("name", "").strip() or "无名旅伴"
    avatar = request.form.get("avatar", dialogue.AVATARS[0]["id"])
    persona = request.form.get("persona", "").strip()
    profile = request.form.get("profile", "").strip()
    speaking_style = request.form.get("speaking_style", "calm")
    distraction_attitude = request.form.get("distraction_attitude", "tolerant")

    conn = get_db()
    conn.execute(
        """INSERT INTO agents
           (user_id, name, avatar, persona, profile, speaking_style, distraction_attitude, created_at)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
        (user["id"], name, avatar, persona, profile, speaking_style, distraction_attitude, db.now_iso()),
    )
    conn.commit()
    return redirect(url_for("agents_list"))


@app.route("/agents/<int:agent_id>/edit", methods=["GET", "POST"])
@login_required
def agent_edit(agent_id):
    user = current_user()
    agent = get_owned_agent(agent_id, user["id"])
    if agent is None:
        return redirect(url_for("agents_list"))

    if request.method == "GET":
        return render_template("agent_form.html", agent=agent)

    name = request.form.get("name", "").strip() or agent["name"]
    avatar = request.form.get("avatar", agent["avatar"])
    persona = request.form.get("persona", "").strip()
    profile = request.form.get("profile", "").strip()
    speaking_style = request.form.get("speaking_style", agent["speaking_style"])
    distraction_attitude = request.form.get("distraction_attitude", agent["distraction_attitude"])

    conn = get_db()
    conn.execute(
        """UPDATE agents SET name=?, avatar=?, persona=?, profile=?, speaking_style=?, distraction_attitude=?
           WHERE id=? AND user_id=?""",
        (name, avatar, persona, profile, speaking_style, distraction_attitude, agent_id, user["id"]),
    )
    conn.commit()
    return redirect(url_for("agents_list"))


@app.route("/agents/<int:agent_id>/delete", methods=["POST"])
@login_required
def agent_delete(agent_id):
    user = current_user()
    conn = get_db()
    # Soft delete: a hard DELETE would cascade into tasks and story_logs, and the
    # records center should keep those. Chat history and unfinished tasks go.
    cur = conn.execute(
        "UPDATE agents SET deleted_at = ? WHERE id = ? AND user_id = ? AND deleted_at IS NULL",
        (db.now_iso(), agent_id, user["id"]),
    )
    if cur.rowcount:
        conn.execute("DELETE FROM messages WHERE agent_id = ? AND user_id = ?", (agent_id, user["id"]))
        conn.execute(
            "DELETE FROM tasks WHERE agent_id = ? AND user_id = ? AND status = 'in_progress'",
            (agent_id, user["id"]),
        )
    conn.commit()
    return redirect(url_for("agents_list"))


# ----------------------------------------------------------- chat routes
@app.route("/agents/<int:agent_id>/chat")
@login_required
def chat(agent_id):
    user = current_user()
    agent = get_owned_agent(agent_id, user["id"])
    if agent is None:
        return redirect(url_for("agents_list"))

    conn = get_db()
    messages = conn.execute(
        "SELECT * FROM messages WHERE agent_id = ? AND user_id = ? ORDER BY id ASC",
        (agent_id, user["id"]),
    ).fetchall()

    if not messages:
        intro = llm_engine.generate_intro(agent)
        conn.execute(
            "INSERT INTO messages (user_id, agent_id, sender, content, created_at) VALUES (?,?,?,?,?)",
            (user["id"], agent_id, "agent", intro, db.now_iso()),
        )
        conn.commit()
        messages = conn.execute(
            "SELECT * FROM messages WHERE agent_id = ? AND user_id = ? ORDER BY id ASC",
            (agent_id, user["id"]),
        ).fetchall()

    # an in-progress task (if any) locks the chat input, per spec (专注期间暂停角色聊天)
    active_task = conn.execute(
        """SELECT * FROM tasks WHERE agent_id = ? AND user_id = ? AND status = 'in_progress'
           ORDER BY id DESC LIMIT 1""",
        (agent_id, user["id"]),
    ).fetchone()

    avatar_map = {a["id"]: a for a in dialogue.AVATARS}
    llm_ready = llm_engine.is_available()
    return render_template(
        "chat.html", agent=agent, messages=messages, active_task=active_task,
        avatar_map=avatar_map, llm_ready=llm_ready,
    )


@app.route("/agents/<int:agent_id>/chat/reset", methods=["POST"])
@login_required
def chat_reset(agent_id):
    """Start a fresh topic: wipe this agent's chat history (the LLM context comes
    from `messages`), but keep tasks and story_logs for the records center."""
    user = current_user()
    agent = get_owned_agent(agent_id, user["id"])
    if agent is None:
        return redirect(url_for("agents_list"))
    conn = get_db()
    conn.execute("DELETE FROM messages WHERE agent_id = ? AND user_id = ?", (agent_id, user["id"]))
    conn.commit()
    # chat() re-seeds an intro line when the history is empty
    return redirect(url_for("chat", agent_id=agent_id))


@app.route("/agents/<int:agent_id>/chat/send", methods=["POST"])
@login_required
def chat_send(agent_id):
    user = current_user()
    agent = get_owned_agent(agent_id, user["id"])
    if agent is None:
        return jsonify({"error": "not_found"}), 404

    payload = request.get_json(silent=True) or {}
    text = (payload.get("text") or "").strip()
    force_task = bool(payload.get("force_task"))
    if not text and not force_task:
        return jsonify({"error": "empty"}), 400

    conn = get_db()
    if text:
        conn.execute(
            "INSERT INTO messages (user_id, agent_id, sender, content, created_at) VALUES (?,?,?,?,?)",
            (user["id"], agent_id, "user", text, db.now_iso()),
        )

    # when the toolbar's "唤起委托" is tapped with nothing typed, feed the
    # generator a neutral placeholder instead of an empty string
    effective_text = text or "（主动想要接一份委托，没有说明具体想做什么）"

    history = get_recent_history(conn, agent_id, user["id"])
    reply_text, task_offer = llm_engine.generate_reply(agent, history, effective_text, force=force_task)
    conn.execute(
        "INSERT INTO messages (user_id, agent_id, sender, content, created_at) VALUES (?,?,?,?,?)",
        (user["id"], agent_id, "agent", reply_text, db.now_iso()),
    )
    conn.commit()

    resp = {"reply": reply_text, "task_offer": None}
    if task_offer:
        name, desc = task_offer
        resp["task_offer"] = {"name": name, "desc": desc}
    return jsonify(resp)


# ----------------------------------------------------------- task routes
@app.route("/agents/<int:agent_id>/tasks/start", methods=["POST"])
@login_required
def task_start(agent_id):
    user = current_user()
    agent = get_owned_agent(agent_id, user["id"])
    if agent is None:
        return jsonify({"error": "not_found"}), 404

    data = request.get_json(silent=True) or {}
    task_name = (data.get("task_name") or "").strip() or "专注委托"
    task_desc = (data.get("task_desc") or "").strip()
    try:
        duration_min = int(data.get("duration_min", 25))
    except (TypeError, ValueError):
        duration_min = 25
    duration_min = max(1, min(180, duration_min))

    conn = get_db()
    conn.execute(
        """INSERT INTO tasks
           (user_id, agent_id, task_name, task_desc, duration_min, status, started_at, created_at)
           VALUES (?, ?, ?, ?, ?, 'in_progress', ?, ?)""",
        (user["id"], agent_id, task_name, task_desc, duration_min, db.now_iso(), db.now_iso()),
    )
    conn.commit()
    task_id = conn.execute("SELECT last_insert_rowid() AS id").fetchone()["id"]
    return jsonify({"task_id": task_id, "focus_url": url_for("focus", agent_id=agent_id, task_id=task_id)})


@app.route("/agents/<int:agent_id>/tasks/<int:task_id>/focus")
@login_required
def focus(agent_id, task_id):
    user = current_user()
    agent = get_owned_agent(agent_id, user["id"])
    if agent is None:
        return redirect(url_for("agents_list"))
    conn = get_db()
    task = conn.execute(
        "SELECT * FROM tasks WHERE id = ? AND agent_id = ? AND user_id = ?",
        (task_id, agent_id, user["id"]),
    ).fetchone()
    if task is None or task["status"] != "in_progress":
        return redirect(url_for("chat", agent_id=agent_id))
    # Remaining time is derived from started_at so the countdown survives page
    # refreshes and background-tab throttling. Computed server-side so the
    # browser's clock doesn't need to agree with ours.
    elapsed = (datetime.now(timezone.utc) - datetime.fromisoformat(task["started_at"])).total_seconds()
    remaining_sec = max(0, int(task["duration_min"] * 60 - elapsed))
    return render_template("focus.html", agent=agent, task=task, remaining_sec=remaining_sec)


NOTE_MAX_LEN = 2000


@app.route("/tasks/<int:task_id>/note", methods=["POST"])
@login_required
def task_note(task_id):
    """Autosave for the notes box on the focus page."""
    user = current_user()
    note = str((request.get_json(silent=True) or {}).get("note", ""))[:NOTE_MAX_LEN]
    conn = get_db()
    cur = conn.execute(
        "UPDATE tasks SET note = ? WHERE id = ? AND user_id = ?", (note, task_id, user["id"])
    )
    conn.commit()
    if cur.rowcount == 0:
        return jsonify({"error": "not_found"}), 404
    return jsonify({"ok": True})


@app.route("/tasks/<int:task_id>/deliver", methods=["POST"])
@login_required
def task_deliver(task_id):
    user = current_user()
    conn = get_db()
    task = conn.execute(
        "SELECT * FROM tasks WHERE id = ? AND user_id = ?", (task_id, user["id"])
    ).fetchone()
    if task is None:
        return jsonify({"error": "not_found"}), 404

    payload = request.get_json(silent=True) or {}
    outcome = payload.get("outcome", "")
    if outcome not in ("complete", "distracted", "gave_up"):
        return jsonify({"error": "bad_outcome"}), 400
    note = str(payload.get("note", task["note"]))[:NOTE_MAX_LEN]

    agent = get_owned_agent(task["agent_id"], user["id"])

    conn.execute(
        "UPDATE tasks SET status = ?, outcome = ?, note = ?, ended_at = ? WHERE id = ?",
        (outcome, outcome, note, db.now_iso(), task_id),
    )

    line = llm_engine.generate_outcome_line(agent, task["task_name"], task["duration_min"], outcome)
    conn.execute(
        "INSERT INTO messages (user_id, agent_id, sender, content, created_at) VALUES (?,?,?,?,?)",
        (user["id"], agent["id"], "agent", line, db.now_iso()),
    )

    story = dialogue.build_story_entry(agent["name"], task["task_name"], task["duration_min"], outcome)
    conn.execute(
        """INSERT INTO story_logs (user_id, agent_id, task_id, entry_date, content, created_at)
           VALUES (?, ?, ?, ?, ?, ?)""",
        (user["id"], agent["id"], task_id, date.today().isoformat(), story, db.now_iso()),
    )
    conn.commit()

    # test trigger (see mailbox.DEBUG_TRIGGER): write today's letter right now
    if note.rstrip().endswith(mailbox.DEBUG_TRIGGER):
        mailbox.write_debug_letter(conn, user["id"], agent)

    return jsonify({
        "line": line,
        "chat_url": url_for("chat", agent_id=agent["id"]),
    })


# --------------------------------------------------------- records center
@app.route("/stories/<int:story_id>/delete", methods=["POST"])
@login_required
def story_delete(story_id):
    """Remove one story-log entry. The underlying task row is kept, so the
    dashboard stats (focus minutes, completion rate) don't change."""
    user = current_user()
    conn = get_db()
    cur = conn.execute("DELETE FROM story_logs WHERE id = ? AND user_id = ?", (story_id, user["id"]))
    conn.commit()
    if cur.rowcount == 0:
        return jsonify({"error": "not_found"}), 404
    return jsonify({"ok": True})


@app.route("/records")
@login_required
def records():
    user = current_user()
    conn = get_db()

    tasks = conn.execute(
        "SELECT * FROM tasks WHERE user_id = ? AND status != 'in_progress' ORDER BY id DESC",
        (user["id"],),
    ).fetchall()

    today = date.today()
    month_prefix = f"{today.year:04d}-{today.month:02d}"
    month_tasks = [t for t in tasks if (t["ended_at"] or "").startswith(month_prefix)
                   or (t["created_at"] or "").startswith(month_prefix)]

    total_minutes = sum(t["duration_min"] for t in month_tasks)
    completed = sum(1 for t in month_tasks if t["outcome"] == "complete")
    total_count = len(month_tasks)
    completion_rate = round(100 * completed / total_count) if total_count else 0

    # simple calendar check-in: distinct days this month with any task activity
    checkin_days = sorted({
        (t["ended_at"] or t["created_at"] or "")[:10] for t in month_tasks
        if (t["ended_at"] or t["created_at"])
    })

    stories = conn.execute(
        """SELECT s.*, a.name AS agent_name, t.note AS task_note, t.task_desc AS task_desc FROM story_logs s
           JOIN agents a ON a.id = s.agent_id
           LEFT JOIN tasks t ON t.id = s.task_id
           WHERE s.user_id = ? ORDER BY s.id DESC""",
        (user["id"],),
    ).fetchall()

    return render_template(
        "records.html",
        total_minutes=total_minutes,
        completion_rate=completion_rate,
        total_count=total_count,
        checkin_days=checkin_days,
        today=today,
        stories=stories,
    )


# ---------------------------------------------------------------- mailbox
@app.route("/mailbox")
@login_required
def mailbox_list():
    user = current_user()
    letters = get_db().execute(
        """SELECT l.*, a.name AS agent_name, a.avatar AS agent_avatar FROM letters l
           JOIN agents a ON a.id = l.agent_id
           WHERE l.user_id = ? ORDER BY l.letter_date DESC""",
        (user["id"],),
    ).fetchall()
    return render_template(
        "mailbox.html", letters=letters, letter_time=mailbox.LETTER_TIME.strftime("%H:%M"),
        avatar_map={a["id"]: a for a in dialogue.AVATARS},
    )


@app.route("/letters/<int:letter_id>")
@login_required
def letter_view(letter_id):
    user = current_user()
    conn = get_db()
    letter = conn.execute(
        """SELECT l.*, a.name AS agent_name, a.avatar AS agent_avatar FROM letters l
           JOIN agents a ON a.id = l.agent_id
           WHERE l.id = ? AND l.user_id = ?""",
        (letter_id, user["id"]),
    ).fetchone()
    if letter is None:
        return redirect(url_for("mailbox_list"))
    if letter["read_at"] is None:
        conn.execute("UPDATE letters SET read_at = ? WHERE id = ?", (db.now_iso(), letter_id))
        conn.commit()
    return render_template(
        "letter.html", letter=letter, avatar_map={a["id"]: a for a in dialogue.AVATARS},
    )


if __name__ == "__main__":
    db.init_db()
    # With debug=True the reloader runs this file twice; only the child process
    # (WERKZEUG_RUN_MAIN=true) serves requests, so start the scheduler only there.
    if os.environ.get("WERKZEUG_RUN_MAIN") == "true":
        mailbox.start_scheduler()
    app.run(host="127.0.0.1", port=5000, debug=True)
